---
  - name: "Setup local Fedora system (root)"
    hosts: localhost
    connection: local 
    tasks:  

    - name: "Set hostname" 
      ansible.builtin.hostname:
        name: wks01.prymal.linux
        use: systemd

    - name: "Install rpm fusion repo "
      ansible.builtin.dnf:
        name: 
            - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-branched.noarch.rpm'
            - 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-branched.noarch.rpm'
        disable_gpg_check: yes
        state: present

    - name: "Import a key from a url"
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: "Create vscode.repo"
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: "Install packages"
      ansible.builtin.dnf:
        name: 
            - neofetch 
            - tilix
            - gnome-tweaks
            - starship 
            - powerline-fonts
            - fontawesome-fonts
            - fira-code-fonts
            - toolbox
            - flatpak-builder
            - the_silver_searcher
            - bpytop
            - code
            - git
            - bash-completion
        update_cache: yes
        state: present
        
    - name: "Install media codecs"
      ansible.builtin.dnf:
        name: 
            - gstreamer1-plugins-bad-* 
            - gstreamer1-plugins-good-* 
            - gstreamer1-plugins-base
            - gstreamer1-plugin-openh264 
            - gstreamer1-libav
        exclude: gstreamer1-plugins-bad-free-devel
        state: present
        
    - name: "Remove unwanted packages"
      ansible.builtin.dnf:
        name: 
            - PackageKit-command-not-found
            - PackageKit-gstreamer-plugin
        state: absent

    - name: "Set default shell to fish"
      ansible.builtin.user:
        name: root
        shell: /bin/bash
